name: Compile MRS Ruleset

on:
  # Запуск вручную кнопкой в интерфейсе GitHub
  workflow_dispatch:
  # Автоматический запуск каждые 24 часа
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Install Official Mihomo
        run: |
          # Скачиваем официальный релиз напрямую из репозитория MetaCubeX/mihomo
          curl -sSL "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz" -o coupons.gz
          gunzip coupons.gz
          chmod +x coupons
          sudo mv coupons /usr/local/bin/mihomo

      - name: Compile YAML to MRS
        run: |
          echo "Starting compilation of ads.yaml..."
          
          # Запускаем компиляцию локального файла ads.yaml из вашего репозитория
          # timeout на 5 секунд защитит от зависания прокси-сервера
          timeout 5s mihomo cli ruleset compile ads.yaml -o category-ads-all.mrs || true
          
          # Проверяем результат
          if [ -s category-ads-all.mrs ]; then
            echo "Success! Binary MRS rule-provider created."
          else
            echo "Error: Compilation failed." && exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ads-mrs-ruleset
          path: category-ads-all.mrs

      # (Опционально) Публикация в релизы, чтобы была постоянная ссылка
      - name: Release MRS File
        uses: softprops/action-gh-release@v3
        if: success()
        with:
          tag_name: latest
          files: category-ads-all.mrs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
