name: Compile MRS Ruleset

on:
  # Запуск вручную кнопкой в интерфейсе GitHub
  workflow_dispatch:
  # Автоматический запуск каждые 24 часа
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6


      - name: Install Official Mihomo
        run: |
          # Скачиваем официальный релиз напрямую из репозитория MetaCubeX/mihomo
          curl -sSL "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz" -o coupons.gz
          gunzip coupons.gz
          chmod +x coupons
          sudo mv coupons /usr/local/bin/mihomo

      - name: Compile YAML to MRS
        run: |
          echo "Starting official rule-set conversion..."
          
          # Синтаксис: mihomo convert-ruleset [поведение] [исходный-формат] [входной-файл] [выходной-файл]
          mihomo convert-ruleset domain yaml ads.yaml category-ads-all.mrs
          
          echo "Conversion finished perfectly!"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ads-mrs-ruleset
          path: category-ads-all.mrs

      # (Опционально) Публикация в релизы, чтобы была постоянная ссылка
      - name: Release MRS File
        uses: softprops/action-gh-release@v3
        if: success()
        with:
          tag_name: latest
          files: category-ads-all.mrs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
